services:
  metric-forecaster:
    restart: always
    build:
      context: .
    ports:
      # use 10000 + gitlab project ID (1646) to avoid host port collisions
      # This is only for referencing from the host.
      # Within the docker-compose environment you would use http://metric-forecaster.
      - 11646:80
    env_file:
      - "docker.env"
