services:
  metric-forecaster:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - "docker.env"

  mysql:
    image: mysql:8
    ports:
      - "3306:3006"
    volumes:
      - ".mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "metric_forecaster"
      MYSQL_ROOT_PASSWORD: "DBROOTPASSWORD"
